FROM openjdk:8-jre-alpine

RUN mkdir /liquibase
ADD https://github.com/liquibase/liquibase/releases/download/v4.5.1/liquibase-4.5.1.tar.gz /liquibase/
RUN tar -xzf /liquibase/liquibase-4.5.1.tar.gz -C /liquibase/
RUN chmod +x /liquibase/liquibase
RUN rm /liquibase/liquibase-4.5.1.tar.gz

WORKDIR /liquibase

COPY ./changelog.xml /liquibase/

ENTRYPOINT ["./liquibase"]